spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Music-Shop?useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompilantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 010Oracle
    plataform: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
